name: cloudflare-go-build-win
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-go@v3
#        with:
#          go-version: '>=1.21.1'
      - name: building golang
        run: |
          dir
          cd src
          go version
          go env
          ./make.bat
          cd ../../
          & "c:/Program Files/7-Zip/7z.exe" a golang.7z -r go
      - uses: actions/upload-artifact@v4
        with:
          name: go-cloudflare2
          path: D:/a/go/golang.7z
